// Products actions
export const PRODUCTS = {
  SET_LOADING_REQUEST: "PRODUCTS_SET_LOADING_REQUEST",
  SET_LOADING: "PRODUCTS_SET_LOADING",
  LOAD_REQUEST: "PRODUCTS_LOAD_REQUEST",
  LOAD_SUCCESS: "PRODUCTS_LOAD_SUCCESS",
  ADD_REQUEST: "PRODUCTS_ADD_REQUEST",
};
